// SPDX-FileCopyrightText: 2026 Blair Hamilton
// SPDX-License-Identifier: Apache-2.0

// Command widthgen turns Unicode's EastAsianWidth.txt into the table the
// line editor measures with.
//
// It exists because this module has no dependencies of its own and a width
// table cannot be derived from the standard library: Go ships the general
// categories, so combining marks come free, but not East Asian Width. The
// table is generated into the repository rather than imported, and this is
// the program that made it.
//
// Usage:
//
//	go run ./internal/widthgen -in EastAsianWidth.txt -out repl/eastasianwidth.go
//
// The input is https://www.unicode.org/Public/<version>/ucd/EastAsianWidth.txt
// and is not checked in: it is read once, and what the build uses is the Go
// file this writes.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

type interval struct{ lo, hi rune }

func main() {
	in := flag.String("in", "EastAsianWidth.txt", "path to EastAsianWidth.txt")
	out := flag.String("out", "repl/eastasianwidth.go", "Go file to write")
	flag.Parse()

	f, err := os.Open(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, "widthgen:", err)
		os.Exit(1)
	}
	defer func() { _ = f.Close() }()

	version := ""
	var wide []interval
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if version == "" && strings.HasPrefix(line, "# EastAsianWidth-") {
			version = strings.TrimSuffix(strings.TrimPrefix(line, "# EastAsianWidth-"), ".txt")
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		fields := strings.Split(line, ";")
		if len(fields) < 2 {
			continue
		}
		// W is wide and F is fullwidth. A is *ambiguous* and is deliberately
		// left out: it is one cell in a Western locale and two in an East
		// Asian one, so it is a property of the terminal rather than of the
		// character, and every implementation that guesses is wrong half the
		// time.
		switch strings.TrimSpace(fields[1]) {
		case "W", "F":
		default:
			continue
		}
		lo, hi, ok := parseRange(strings.TrimSpace(fields[0]))
		if !ok {
			continue
		}
		wide = append(wide, interval{lo, hi})
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "widthgen:", err)
		os.Exit(1)
	}
	if err := write(*out, version, merge(wide)); err != nil {
		fmt.Fprintln(os.Stderr, "widthgen:", err)
		os.Exit(1)
	}
}

func parseRange(s string) (lo, hi rune, ok bool) {
	first, last, found := strings.Cut(s, "..")
	a, err := strconv.ParseUint(first, 16, 32)
	if err != nil {
		return 0, 0, false
	}
	if !found {
		return rune(a), rune(a), true
	}
	b, err := strconv.ParseUint(last, 16, 32)
	if err != nil {
		return 0, 0, false
	}
	return rune(a), rune(b), true
}

// merge joins ranges that touch, which the data file leaves separate because
// it groups by general category as well as by width.
func merge(in []interval) []interval {
	sort.Slice(in, func(i, j int) bool { return in[i].lo < in[j].lo })
	var out []interval
	for _, iv := range in {
		if n := len(out); n > 0 && iv.lo <= out[n-1].hi+1 {
			if iv.hi > out[n-1].hi {
				out[n-1].hi = iv.hi
			}
			continue
		}
		out = append(out, iv)
	}
	return out
}

func write(path, version string, ranges []interval) error {
	var b strings.Builder
	b.WriteString("// SPDX-FileCopyrightText: 2026 Blair Hamilton\n")
	b.WriteString("// SPDX-License-Identifier: Apache-2.0\n\n")
	b.WriteString("// Code generated by internal/widthgen. DO NOT EDIT.\n\n")
	b.WriteString("package repl\n\n")
	fmt.Fprintf(&b, "// eastAsianWidthVersion is the Unicode version these ranges came from.\n")
	fmt.Fprintf(&b, "// A later one moves characters between classes, and without this nothing\n")
	fmt.Fprintf(&b, "// records which one a given build measured.\n")
	fmt.Fprintf(&b, "const eastAsianWidthVersion = %q\n\n", version)
	fmt.Fprintf(&b, "// wideRanges are the code points East Asian Width calls W or F, which a\n")
	fmt.Fprintf(&b, "// terminal draws in two cells. Ambiguous is not here: it is one cell in a\n")
	fmt.Fprintf(&b, "// Western locale and two in an East Asian one, so it belongs to the\n")
	fmt.Fprintf(&b, "// terminal rather than to the character.\n")
	b.WriteString("var wideRanges = [...][2]rune{\n")
	for _, iv := range ranges {
		fmt.Fprintf(&b, "\t{%#x, %#x},\n", iv.lo, iv.hi)
	}
	b.WriteString("}\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
