// SPDX-FileCopyrightText: 2026 Blair Hamilton
// SPDX-License-Identifier: Apache-2.0

// Command suitecheck fetches a shell's own test suite and runs every file of
// it through both that shell and the dialect binary claiming to be it.
//
// It is a report and never a gate, for the reason `make wild` is not one and
// one more: the corpus is fetched over a network from a third party, so a
// machine with no network has not told us anything about the shell. Every
// reason it cannot run is printed in full and exits 0 — an instrument that
// failed a build because a download did not arrive would be turned off within
// a week, and an instrument that exited quietly would be worse, because zero
// files compared and zero disagreements look identical in a log.
//
// What it prints is counts and this parser's own diagnostics. It never prints
// a line, a token or a path from a fetched file: those are another project's
// expression, CLEANROOM.md's red list covers them, and the carve-out this
// stands on is a carve-out for running a suite rather than for reading one.
//
// # -own: our own suite, the same grader
//
// `make suite` runs this with -own, over the files committed under
// share/suite. It is the same instrument and deliberately so: a column there
// is a suite.Suite with Ours set and its files on disk instead of in an
// archive, and it is graded by the same suite.Sweep, against the same
// reference shell, with the same three numbers. Nothing in -own mode computes
// a score of its own. A second scorer that drifted from the first is a
// failure this repository has made before.
//
// Two things do differ, and both follow from whose files they are. Ours are
// committed and Apache-2.0, so the report names the cases that failed — a
// report that would not say which of our own cases to go and fix is not a
// work list. And core/ runs in every column, so -own additionally asks
// whether the reference shells themselves all wrote the same bytes: that is
// the common-denominator claim in docs/spec/shell-matrix.md turned into a
// measurement rather than an assertion.
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/blairham/sh/internal/suite"
)

func main() {
	var (
		dialect = flag.String("dialect", "bash",
			"which column to run: the dialect binary's name under cmd/")
		bin = flag.String("bin", "",
			"the dialect binary to grade; required")
		buildDir = flag.String("build", "build",
			"directory the suite is fetched into; it is gitignored and nothing here is ever committed")
		timeout = flag.Duration("timeout", suite.DefaultTimeout,
			"how long one file gets under one shell before its process group is killed")
		jobs    = flag.Int("jobs", 4, "how many files to run at once")
		refetch = flag.Bool("refetch", false,
			"fetch the archive again even if the unpacked tree matches the pin")
		only = flag.String("only", "",
			"comma-separated file names to run, for working on the harness itself")
		panel = flag.Bool("panel", false, "print the panel of columns and stop")
		own   = flag.Bool("own", false,
			"grade our own committed suite instead of a fetched one, every column at once")
		ownRoot = flag.String("root", suite.OurRoot,
			"where our own suite lives in the tree")
		ownBins = binSet{}
	)
	flag.Var(ownBins, "own-bin",
		"in -own mode, a dialect binary to grade: dialect=path, repeated")
	flag.Parse()

	if *panel {
		printPanel()
		return
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	if *own {
		if code := runOwn(ctx, *ownRoot, ownBins, *timeout, *jobs, *only); code != 0 {
			os.Exit(code)
		}
		return
	}

	if code := run(ctx, *dialect, *bin, *buildDir, *timeout, *jobs, *refetch, *only); code != 0 {
		os.Exit(code)
	}
}

func run(ctx context.Context, dialect, bin, buildDir string, timeout time.Duration, jobs int, refetch bool, only string) int {
	s, ok := suite.Find(dialect)
	if !ok {
		fmt.Fprintf(os.Stderr, "suitecheck: no column for dialect %q; -panel lists them\n", dialect)
		return 2
	}
	if s.NotYet != "" {
		// Loud, and zero. A column that is not built is a fact about this
		// instrument and printing it is the whole reason the unbuilt columns
		// are rows at all: a missing column that says nothing reads as a
		// column that passed.
		fmt.Printf("%s: not yet a column of this instrument.\n\n  %s\n\n", s.Name, wrap(s.NotYet, "  "))
		printPanel()
		return 0
	}
	if bin == "" {
		fmt.Fprintln(os.Stderr, "suitecheck: -bin is required: the dialect binary to grade")
		return 2
	}
	bin, err := suite.Shell(bin)
	if err != nil {
		fmt.Fprintf(os.Stderr, "suitecheck: -bin: %v\n", err)
		return 2
	}

	reference, found := suite.Locate(s.Lookup)
	if !found {
		skip(fmt.Sprintf("no %s on this machine to be the oracle", s.Name),
			"The reference shell is the oracle, never the suite's own expected output: "+
				"those files were generated by a different build of a different version. "+
				"Looked in "+strings.Join(s.Lookup, ", ")+".")
		return 0
	}

	dir, err := suite.Fetch(ctx, s, buildDir, refetch)
	switch {
	case errors.Is(err, suite.ErrOffline):
		skip("the suite could not be fetched",
			"It is never committed — it is "+licenseNote(s)+" and this repository is Apache-2.0, "+
				"so committing it would relicense the tree by accident. That means a machine "+
				"with no network cannot run this column.\n\n  "+err.Error())
		return 0
	case errors.Is(err, suite.ErrDigest):
		fmt.Fprintf(os.Stderr, "suitecheck: %v\n\n", err)
		fmt.Fprintln(os.Stderr, "  The archive is pinned by digest so that two runs a month apart are")
		fmt.Fprintln(os.Stderr, "  comparable. Grading whatever arrived would move every number in the")
		fmt.Fprintln(os.Stderr, "  report with nothing in the report saying so.")
		return 1
	case err != nil:
		fmt.Fprintf(os.Stderr, "suitecheck: %v\n", err)
		return 1
	}

	helpers, err := suite.BuildHelpers(ctx, s, dir)
	if errors.Is(err, suite.ErrNoCompiler) {
		skip("the suite's helpers cannot be built",
			"Without them the whole suite scores zero for reasons that have nothing to do "+
				"with us: the calls fail under both shells and the two failures match, so the "+
				"run reads as agreement on an error message.")
		return 0
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "suitecheck: building the suite's helpers: %v\n", err)
		return 1
	}

	opts := suite.Options{Timeout: timeout, Jobs: jobs, Only: names(only)}
	rep, err := suite.Sweep(ctx, s, dir, bin, reference, opts)
	if err != nil {
		fmt.Fprintf(os.Stderr, "suitecheck: %v\n", err)
		return 1
	}
	rep.ReferenceVersion = suite.Version(ctx, reference)
	rep.Helpers = helpers
	printReport(rep)
	printPanel()
	return 0
}

func names(list string) map[string]bool {
	if list == "" {
		return nil
	}
	set := map[string]bool{}
	for _, n := range strings.Split(list, ",") {
		if n = strings.TrimSpace(n); n != "" {
			set[n] = true
		}
	}
	return set
}

func licenseNote(s suite.Suite) string {
	if s.Name == "bash" {
		return "GPLv3"
	}
	return "another project's work"
}

// skip prints the reason a column did not run, in full, and returns nothing.
// The wording is deliberate: a skip is a fact about the machine, and the
// thing that must not happen is for it to be mistaken for a result.
func skip(what, why string) {
	fmt.Printf("SKIPPED — %s\n\n  %s\n\n", what, wrap(why, "  "))
}

func printReport(rep suite.Report) {
	s := rep.Suite
	fmt.Printf("%s's own suite, %s — %d files (%s)\n", s.Name, s.Version, rep.Files, s.Ext)
	fmt.Printf("  oracle   %s — %s\n", rep.Reference, rep.ReferenceVersion)
	fmt.Printf("  ours     %s\n", rep.Ours)
	if len(rep.Helpers) > 0 {
		fmt.Printf("  helpers  %s, built from the suite's own C\n", strings.Join(rep.Helpers, ", "))
	}
	fmt.Println()

	fmt.Printf("  parsed          %-9s %5.1f%%   our parser read the whole file\n",
		fmt.Sprintf("%d/%d", rep.Parsed, rep.Files), 100*rep.ParseRate())
	fmt.Printf("  strict          %-9s %5.1f%%   every byte and the status identical\n",
		fmt.Sprintf("%d/%d", rep.Strict, rep.Scored), 100*rep.StrictRate())
	fmt.Printf("  line agreement  %-9s %5.1f%%   longest common subsequence, by line\n",
		"", 100*rep.LineRate())
	fmt.Printf("                  %-9s %5.1f%%   the same, unweighted per file\n",
		"", 100*rep.MeanFile)
	fmt.Println()

	fmt.Printf("  not scored       %d unstable · %d oracle hung · %d dialect hung\n",
		rep.Unstable, rep.OracleHung, rep.DialectHung)
	if rep.OracleFailed+rep.DialectFailed > 0 {
		fmt.Printf("                   %d oracle · %d dialect never started at all\n",
			rep.OracleFailed, rep.DialectFailed)
	}
	fmt.Println("                   unstable: the oracle did not repeat itself, so the file is")
	fmt.Println("                     evidence about neither shell — a pid, a clock, an order.")
	fmt.Println("                   oracle hung: a harness fault. The shell that wrote the file")
	fmt.Println("                     does not hang on it, so this is load or too tight a bound.")
	fmt.Println("                   dialect hung: a hang we published. Different finding, kept apart.")
	if rep.LineCapped > 0 {
		fmt.Printf("  capped           %d files printed more lines than the comparison's bound\n", rep.LineCapped)
	}
	fmt.Println()

	fmt.Println("  The three numbers are three because each lies alone. Strict reads as")
	fmt.Println("  catastrophe — one disagreement forfeits a file of hundreds of assertions.")
	fmt.Println("  Line agreement reads as triumph — most lines are text a shell echoed back.")
	fmt.Println("  Parsed explains both: this parser reads a file whole before running any of")
	fmt.Println("  it, so one refused construct forfeits a file that might have agreed line")
	fmt.Println("  for line.")
	fmt.Println()

	if len(rep.Causes) == 0 {
		fmt.Println("  nothing was refused by the parser")
	} else {
		fmt.Println("  file-stopping constructs, by files forfeited")
		fmt.Println("  (this parser's own diagnostic, with the position and any word from the")
		fmt.Println("   file removed — the fetched text that provoked it is never printed)")
		for _, c := range rep.Causes {
			fmt.Printf("    %4d  %s\n", c.Files, c.Reason)
		}
	}
	fmt.Println()

	if len(rep.StatusPairs) > 0 {
		fmt.Println("  exit status of the files that ran and disagreed  (ours / oracle)")
		fmt.Println("  (numbers, because our runtime diagnostics would quote the file back;")
		fmt.Println("   -1 is a run that ended on a signal or never started)")
		for _, p := range rep.StatusPairs {
			fmt.Printf("    %4d  %d / %d\n", p.Files, p.Ours, p.Reference)
		}
		fmt.Println()
	}
}

// printPanel prints every column, built and unbuilt, every time.
//
// Always, and not only when one is asked for. The multi-dialect shape is the
// point of this instrument — a bash-only one would bend the substrate toward
// bash, which is what this project's premise forbids — and a column that is
// not built has to be visible as a column rather than as a silence.
func printPanel() {
	fmt.Println("  columns")
	for _, s := range suite.Panel {
		state := "ready"
		if s.NotYet != "" {
			state = "not yet"
		}
		version := s.Version
		if version == "" {
			version = "—"
		}
		fmt.Printf("    %-7s %-8s %-8s make %s-suite\n", s.Name, version, state, s.Dialect)
		if s.NotYet != "" {
			fmt.Printf("      %s\n", wrap(s.NotYet, "      "))
		}
	}
	fmt.Println()
	fmt.Println("  Nothing fetched here is ever committed. It lands under the gitignored build")
	fmt.Println("  directory, in a tree named for the distribution so that `make wild` refuses")
	fmt.Println("  to open it, and only the suite is unpacked — the shell's own source streams")
	fmt.Println("  past without reaching the disk, and neither does the suite's expected output.")
}

// wrap folds a reason to a readable width at the given indent.
func wrap(text, indent string) string {
	const width = 74
	var out strings.Builder
	line := 0
	for i, word := range strings.Fields(text) {
		if line > 0 && line+1+len(word) > width {
			out.WriteString("\n" + indent)
			line = 0
		} else if i > 0 {
			out.WriteString(" ")
			line++
		}
		out.WriteString(word)
		line += len(word)
	}
	return out.String()
}
