// SPDX-FileCopyrightText: 2026 Blair Hamilton
// SPDX-License-Identifier: Apache-2.0

package repl

// The capability names, in the order a compiled terminal description stores
// them.
//
// A compiled description is three arrays and no names: a byte per boolean, a
// number per numeric capability and an offset per string, each at a position
// the format fixes and never writes down. So a reader needs the position of
// every capability, and this file is that — the boolean at index 7 is `hc`,
// the number at index 13 is `colors`, the string at index 19 is `cuu1`.
//
// # Where the order came from, because it is not in any document
//
// terminfo(5) tabulates every capability with its terminfo name, its termcap
// code and what it does, and this file's two name columns are that table. It
// tabulates them **alphabetically by variable name**, which is not the order
// the arrays use, so the index had to be measured rather than read.
//
// It was measured with `tic`, 2026-09-11, which is the oracle discipline
// docs/spec/oracle.md describes applied to a data format: compile a
// description that sets one capability and see which slot moved.
//
//   - Strings: one description setting all 386 named string capabilities to a
//     distinct marker, compiled once. Every offset in the compiled file then
//     names its own index, and all 386 resolved with none left over.
//   - Numbers: the same trick with a distinct value per capability, one
//     compile, 33 resolved.
//   - Booleans: 37 compiles, one capability each, because a boolean carries
//     no value to tell two of them apart.
//
// # The obsolete tail, and the eight slots with no name
//
// The arrays are longer than the documented set: 44 booleans, 39 numbers and
// 413 strings against terminfo(5)'s 37, 33 and 386. The difference is a tail
// of capabilities the manual no longer lists and the format still stores, and
// they are not decoration — measured against zsh 5.9.2, `$terminfo` under
// `TERM=dumb` has exactly 50 keys and 44 of them are booleans, so *every*
// boolean name answers whether the description carries it or not, the
// obsolete ones included. `xterm-256color` stores 38 booleans, the last of
// which is `OTbs`, and zsh reports it as `yes`.
//
// Those names were found by running `infocmp` over the descriptions that use
// the tail and probing each name back through `tic` the same way, which
// leaves eight string slots — 386 through 393 — with no name. Nothing names
// them because nothing uses them: a sweep of all 2,684 descriptions in
// /usr/share/terminfo on this machine populates string slots 394, 396, 397,
// 399, 411 and 412 and no other slot past 385. An unnamed slot is skipped
// rather than guessed, which costs a capability no real description has.

// terminfoName is one capability under both naming systems: terminfo's long
// name, which `$terminfo` is keyed by, and termcap's two-letter code, which
// `$termcap` is keyed by. Both columns are terminfo(5)'s.
type terminfoName struct {
	terminfo string
	termcap  string
}

// terminfoBooleanNames is the boolean array's index order.
var terminfoBooleanNames = []terminfoName{
	{terminfo: "bw", termcap: "bw"},
	{terminfo: "am", termcap: "am"},
	{terminfo: "xsb", termcap: "xb"},
	{terminfo: "xhp", termcap: "xs"},
	{terminfo: "xenl", termcap: "xn"},
	{terminfo: "eo", termcap: "eo"},
	{terminfo: "gn", termcap: "gn"},
	{terminfo: "hc", termcap: "hc"},
	{terminfo: "km", termcap: "km"},
	{terminfo: "hs", termcap: "hs"},
	{terminfo: "in", termcap: "in"},
	{terminfo: "da", termcap: "da"},
	{terminfo: "db", termcap: "db"},
	{terminfo: "mir", termcap: "mi"},
	{terminfo: "msgr", termcap: "ms"},
	{terminfo: "os", termcap: "os"},
	{terminfo: "eslok", termcap: "es"},
	{terminfo: "xt", termcap: "xt"},
	{terminfo: "hz", termcap: "hz"},
	{terminfo: "ul", termcap: "ul"},
	{terminfo: "xon", termcap: "xo"},
	{terminfo: "nxon", termcap: "nx"},
	{terminfo: "mc5i", termcap: "5i"},
	{terminfo: "chts", termcap: "HC"},
	{terminfo: "nrrmc", termcap: "NR"},
	{terminfo: "npc", termcap: "NP"},
	{terminfo: "ndscr", termcap: "ND"},
	{terminfo: "ccc", termcap: "cc"},
	{terminfo: "bce", termcap: "ut"},
	{terminfo: "hls", termcap: "hl"},
	{terminfo: "xhpa", termcap: "YA"},
	{terminfo: "crxm", termcap: "YB"},
	{terminfo: "daisy", termcap: "YC"},
	{terminfo: "xvpa", termcap: "YD"},
	{terminfo: "sam", termcap: "YE"},
	{terminfo: "cpix", termcap: "YF"},
	{terminfo: "lpix", termcap: "YG"},
	{terminfo: "OTbs", termcap: "bs"},
	{terminfo: "OTns", termcap: "ns"},
	{terminfo: "OTnc", termcap: "nc"},
	{terminfo: "OTMT", termcap: "MT"},
	{terminfo: "OTNL", termcap: "NL"},
	{terminfo: "OTpt", termcap: "pt"},
	{terminfo: "OTxr", termcap: "xr"},
}

// terminfoNumberNames is the numeric array's index order.
var terminfoNumberNames = []terminfoName{
	{terminfo: "cols", termcap: "co"},
	{terminfo: "it", termcap: "it"},
	{terminfo: "lines", termcap: "li"},
	{terminfo: "lm", termcap: "lm"},
	{terminfo: "xmc", termcap: "sg"},
	{terminfo: "pb", termcap: "pb"},
	{terminfo: "vt", termcap: "vt"},
	{terminfo: "wsl", termcap: "ws"},
	{terminfo: "nlab", termcap: "Nl"},
	{terminfo: "lh", termcap: "lh"},
	{terminfo: "lw", termcap: "lw"},
	{terminfo: "ma", termcap: "ma"},
	{terminfo: "wnum", termcap: "MW"},
	{terminfo: "colors", termcap: "Co"},
	{terminfo: "pairs", termcap: "pa"},
	{terminfo: "ncv", termcap: "NC"},
	{terminfo: "bufsz", termcap: "Ya"},
	{terminfo: "spinv", termcap: "Yb"},
	{terminfo: "spinh", termcap: "Yc"},
	{terminfo: "maddr", termcap: "Yd"},
	{terminfo: "mjump", termcap: "Ye"},
	{terminfo: "mcs", termcap: "Yf"},
	{terminfo: "mls", termcap: "Yg"},
	{terminfo: "npins", termcap: "Yh"},
	{terminfo: "orc", termcap: "Yi"},
	{terminfo: "orl", termcap: "Yj"},
	{terminfo: "orhi", termcap: "Yk"},
	{terminfo: "orvi", termcap: "Yl"},
	{terminfo: "cps", termcap: "Ym"},
	{terminfo: "widcs", termcap: "Yn"},
	{terminfo: "btns", termcap: "BT"},
	{terminfo: "bitwin", termcap: "Yo"},
	{terminfo: "bitype", termcap: "Yp"},
	{terminfo: "OTug", termcap: "ug"},
	{terminfo: "OTdC", termcap: "dC"},
	{terminfo: "OTdN", termcap: "dN"},
	{terminfo: "OTdB", termcap: "dB"},
	{terminfo: "OTdT", termcap: "dT"},
	{terminfo: "OTkn", termcap: "kn"},
}

// terminfoStringNames is the string array's index order.
var terminfoStringNames = []terminfoName{
	{terminfo: "cbt", termcap: "bt"},
	{terminfo: "bel", termcap: "bl"},
	{terminfo: "cr", termcap: "cr"},
	{terminfo: "csr", termcap: "cs"},
	{terminfo: "tbc", termcap: "ct"},
	{terminfo: "clear", termcap: "cl"},
	{terminfo: "el", termcap: "ce"},
	{terminfo: "ed", termcap: "cd"},
	{terminfo: "hpa", termcap: "ch"},
	{terminfo: "cmdch", termcap: "CC"},
	{terminfo: "cup", termcap: "cm"},
	{terminfo: "cud1", termcap: "do"},
	{terminfo: "home", termcap: "ho"},
	{terminfo: "civis", termcap: "vi"},
	{terminfo: "cub1", termcap: "le"},
	{terminfo: "mrcup", termcap: "CM"},
	{terminfo: "cnorm", termcap: "ve"},
	{terminfo: "cuf1", termcap: "nd"},
	{terminfo: "ll", termcap: "ll"},
	{terminfo: "cuu1", termcap: "up"},
	{terminfo: "cvvis", termcap: "vs"},
	{terminfo: "dch1", termcap: "dc"},
	{terminfo: "dl1", termcap: "dl"},
	{terminfo: "dsl", termcap: "ds"},
	{terminfo: "hd", termcap: "hd"},
	{terminfo: "smacs", termcap: "as"},
	{terminfo: "blink", termcap: "mb"},
	{terminfo: "bold", termcap: "md"},
	{terminfo: "smcup", termcap: "ti"},
	{terminfo: "smdc", termcap: "dm"},
	{terminfo: "dim", termcap: "mh"},
	{terminfo: "smir", termcap: "im"},
	{terminfo: "invis", termcap: "mk"},
	{terminfo: "prot", termcap: "mp"},
	{terminfo: "rev", termcap: "mr"},
	{terminfo: "smso", termcap: "so"},
	{terminfo: "smul", termcap: "us"},
	{terminfo: "ech", termcap: "ec"},
	{terminfo: "rmacs", termcap: "ae"},
	{terminfo: "sgr0", termcap: "me"},
	{terminfo: "rmcup", termcap: "te"},
	{terminfo: "rmdc", termcap: "ed"},
	{terminfo: "rmir", termcap: "ei"},
	{terminfo: "rmso", termcap: "se"},
	{terminfo: "rmul", termcap: "ue"},
	{terminfo: "flash", termcap: "vb"},
	{terminfo: "ff", termcap: "ff"},
	{terminfo: "fsl", termcap: "fs"},
	{terminfo: "is1", termcap: "i1"},
	{terminfo: "is2", termcap: "is"},
	{terminfo: "is3", termcap: "i3"},
	{terminfo: "if", termcap: "if"},
	{terminfo: "ich1", termcap: "ic"},
	{terminfo: "il1", termcap: "al"},
	{terminfo: "ip", termcap: "ip"},
	{terminfo: "kbs", termcap: "kb"},
	{terminfo: "ktbc", termcap: "ka"},
	{terminfo: "kclr", termcap: "kC"},
	{terminfo: "kctab", termcap: "kt"},
	{terminfo: "kdch1", termcap: "kD"},
	{terminfo: "kdl1", termcap: "kL"},
	{terminfo: "kcud1", termcap: "kd"},
	{terminfo: "krmir", termcap: "kM"},
	{terminfo: "kel", termcap: "kE"},
	{terminfo: "ked", termcap: "kS"},
	{terminfo: "kf0", termcap: "k0"},
	{terminfo: "kf1", termcap: "k1"},
	{terminfo: "kf10", termcap: "k;"},
	{terminfo: "kf2", termcap: "k2"},
	{terminfo: "kf3", termcap: "k3"},
	{terminfo: "kf4", termcap: "k4"},
	{terminfo: "kf5", termcap: "k5"},
	{terminfo: "kf6", termcap: "k6"},
	{terminfo: "kf7", termcap: "k7"},
	{terminfo: "kf8", termcap: "k8"},
	{terminfo: "kf9", termcap: "k9"},
	{terminfo: "khome", termcap: "kh"},
	{terminfo: "kich1", termcap: "kI"},
	{terminfo: "kil1", termcap: "kA"},
	{terminfo: "kcub1", termcap: "kl"},
	{terminfo: "kll", termcap: "kH"},
	{terminfo: "knp", termcap: "kN"},
	{terminfo: "kpp", termcap: "kP"},
	{terminfo: "kcuf1", termcap: "kr"},
	{terminfo: "kind", termcap: "kF"},
	{terminfo: "kri", termcap: "kR"},
	{terminfo: "khts", termcap: "kT"},
	{terminfo: "kcuu1", termcap: "ku"},
	{terminfo: "rmkx", termcap: "ke"},
	{terminfo: "smkx", termcap: "ks"},
	{terminfo: "lf0", termcap: "l0"},
	{terminfo: "lf1", termcap: "l1"},
	{terminfo: "lf10", termcap: "la"},
	{terminfo: "lf2", termcap: "l2"},
	{terminfo: "lf3", termcap: "l3"},
	{terminfo: "lf4", termcap: "l4"},
	{terminfo: "lf5", termcap: "l5"},
	{terminfo: "lf6", termcap: "l6"},
	{terminfo: "lf7", termcap: "l7"},
	{terminfo: "lf8", termcap: "l8"},
	{terminfo: "lf9", termcap: "l9"},
	{terminfo: "rmm", termcap: "mo"},
	{terminfo: "smm", termcap: "mm"},
	{terminfo: "nel", termcap: "nw"},
	{terminfo: "pad", termcap: "pc"},
	{terminfo: "dch", termcap: "DC"},
	{terminfo: "dl", termcap: "DL"},
	{terminfo: "cud", termcap: "DO"},
	{terminfo: "ich", termcap: "IC"},
	{terminfo: "indn", termcap: "SF"},
	{terminfo: "il", termcap: "AL"},
	{terminfo: "cub", termcap: "LE"},
	{terminfo: "cuf", termcap: "RI"},
	{terminfo: "rin", termcap: "SR"},
	{terminfo: "cuu", termcap: "UP"},
	{terminfo: "pfkey", termcap: "pk"},
	{terminfo: "pfloc", termcap: "pl"},
	{terminfo: "pfx", termcap: "px"},
	{terminfo: "mc0", termcap: "ps"},
	{terminfo: "mc4", termcap: "pf"},
	{terminfo: "mc5", termcap: "po"},
	{terminfo: "rep", termcap: "rp"},
	{terminfo: "rs1", termcap: "r1"},
	{terminfo: "rs2", termcap: "r2"},
	{terminfo: "rs3", termcap: "r3"},
	{terminfo: "rf", termcap: "rf"},
	{terminfo: "rc", termcap: "rc"},
	{terminfo: "vpa", termcap: "cv"},
	{terminfo: "sc", termcap: "sc"},
	{terminfo: "ind", termcap: "sf"},
	{terminfo: "ri", termcap: "sr"},
	{terminfo: "sgr", termcap: "sa"},
	{terminfo: "hts", termcap: "st"},
	{terminfo: "wind", termcap: "wi"},
	{terminfo: "ht", termcap: "ta"},
	{terminfo: "tsl", termcap: "ts"},
	{terminfo: "uc", termcap: "uc"},
	{terminfo: "hu", termcap: "hu"},
	{terminfo: "iprog", termcap: "iP"},
	{terminfo: "ka1", termcap: "K1"},
	{terminfo: "ka3", termcap: "K3"},
	{terminfo: "kb2", termcap: "K2"},
	{terminfo: "kc1", termcap: "K4"},
	{terminfo: "kc3", termcap: "K5"},
	{terminfo: "mc5p", termcap: "pO"},
	{terminfo: "rmp", termcap: "rP"},
	{terminfo: "acsc", termcap: "ac"},
	{terminfo: "pln", termcap: "pn"},
	{terminfo: "kcbt", termcap: "kB"},
	{terminfo: "smxon", termcap: "SX"},
	{terminfo: "rmxon", termcap: "RX"},
	{terminfo: "smam", termcap: "SA"},
	{terminfo: "rmam", termcap: "RA"},
	{terminfo: "xonc", termcap: "XN"},
	{terminfo: "xoffc", termcap: "XF"},
	{terminfo: "enacs", termcap: "eA"},
	{terminfo: "smln", termcap: "LO"},
	{terminfo: "rmln", termcap: "LF"},
	{terminfo: "kbeg", termcap: "@1"},
	{terminfo: "kcan", termcap: "@2"},
	{terminfo: "kclo", termcap: "@3"},
	{terminfo: "kcmd", termcap: "@4"},
	{terminfo: "kcpy", termcap: "@5"},
	{terminfo: "kcrt", termcap: "@6"},
	{terminfo: "kend", termcap: "@7"},
	{terminfo: "kent", termcap: "@8"},
	{terminfo: "kext", termcap: "@9"},
	{terminfo: "kfnd", termcap: "@0"},
	{terminfo: "khlp", termcap: "%1"},
	{terminfo: "kmrk", termcap: "%2"},
	{terminfo: "kmsg", termcap: "%3"},
	{terminfo: "kmov", termcap: "%4"},
	{terminfo: "knxt", termcap: "%5"},
	{terminfo: "kopn", termcap: "%6"},
	{terminfo: "kopt", termcap: "%7"},
	{terminfo: "kprv", termcap: "%8"},
	{terminfo: "kprt", termcap: "%9"},
	{terminfo: "krdo", termcap: "%0"},
	{terminfo: "kref", termcap: "&1"},
	{terminfo: "krfr", termcap: "&2"},
	{terminfo: "krpl", termcap: "&3"},
	{terminfo: "krst", termcap: "&4"},
	{terminfo: "kres", termcap: "&5"},
	{terminfo: "ksav", termcap: "&6"},
	{terminfo: "kspd", termcap: "&7"},
	{terminfo: "kund", termcap: "&8"},
	{terminfo: "kBEG", termcap: "&9"},
	{terminfo: "kCAN", termcap: "&0"},
	{terminfo: "kCMD", termcap: "*1"},
	{terminfo: "kCPY", termcap: "*2"},
	{terminfo: "kCRT", termcap: "*3"},
	{terminfo: "kDC", termcap: "*4"},
	{terminfo: "kDL", termcap: "*5"},
	{terminfo: "kslt", termcap: "*6"},
	{terminfo: "kEND", termcap: "*7"},
	{terminfo: "kEOL", termcap: "*8"},
	{terminfo: "kEXT", termcap: "*9"},
	{terminfo: "kFND", termcap: "*0"},
	{terminfo: "kHLP", termcap: "#1"},
	{terminfo: "kHOM", termcap: "#2"},
	{terminfo: "kIC", termcap: "#3"},
	{terminfo: "kLFT", termcap: "#4"},
	{terminfo: "kMSG", termcap: "%a"},
	{terminfo: "kMOV", termcap: "%b"},
	{terminfo: "kNXT", termcap: "%c"},
	{terminfo: "kOPT", termcap: "%d"},
	{terminfo: "kPRV", termcap: "%e"},
	{terminfo: "kPRT", termcap: "%f"},
	{terminfo: "kRDO", termcap: "%g"},
	{terminfo: "kRPL", termcap: "%h"},
	{terminfo: "kRIT", termcap: "%i"},
	{terminfo: "kRES", termcap: "%j"},
	{terminfo: "kSAV", termcap: "!1"},
	{terminfo: "kSPD", termcap: "!2"},
	{terminfo: "kUND", termcap: "!3"},
	{terminfo: "rfi", termcap: "RF"},
	{terminfo: "kf11", termcap: "F1"},
	{terminfo: "kf12", termcap: "F2"},
	{terminfo: "kf13", termcap: "F3"},
	{terminfo: "kf14", termcap: "F4"},
	{terminfo: "kf15", termcap: "F5"},
	{terminfo: "kf16", termcap: "F6"},
	{terminfo: "kf17", termcap: "F7"},
	{terminfo: "kf18", termcap: "F8"},
	{terminfo: "kf19", termcap: "F9"},
	{terminfo: "kf20", termcap: "FA"},
	{terminfo: "kf21", termcap: "FB"},
	{terminfo: "kf22", termcap: "FC"},
	{terminfo: "kf23", termcap: "FD"},
	{terminfo: "kf24", termcap: "FE"},
	{terminfo: "kf25", termcap: "FF"},
	{terminfo: "kf26", termcap: "FG"},
	{terminfo: "kf27", termcap: "FH"},
	{terminfo: "kf28", termcap: "FI"},
	{terminfo: "kf29", termcap: "FJ"},
	{terminfo: "kf30", termcap: "FK"},
	{terminfo: "kf31", termcap: "FL"},
	{terminfo: "kf32", termcap: "FM"},
	{terminfo: "kf33", termcap: "FN"},
	{terminfo: "kf34", termcap: "FO"},
	{terminfo: "kf35", termcap: "FP"},
	{terminfo: "kf36", termcap: "FQ"},
	{terminfo: "kf37", termcap: "FR"},
	{terminfo: "kf38", termcap: "FS"},
	{terminfo: "kf39", termcap: "FT"},
	{terminfo: "kf40", termcap: "FU"},
	{terminfo: "kf41", termcap: "FV"},
	{terminfo: "kf42", termcap: "FW"},
	{terminfo: "kf43", termcap: "FX"},
	{terminfo: "kf44", termcap: "FY"},
	{terminfo: "kf45", termcap: "FZ"},
	{terminfo: "kf46", termcap: "Fa"},
	{terminfo: "kf47", termcap: "Fb"},
	{terminfo: "kf48", termcap: "Fc"},
	{terminfo: "kf49", termcap: "Fd"},
	{terminfo: "kf50", termcap: "Fe"},
	{terminfo: "kf51", termcap: "Ff"},
	{terminfo: "kf52", termcap: "Fg"},
	{terminfo: "kf53", termcap: "Fh"},
	{terminfo: "kf54", termcap: "Fi"},
	{terminfo: "kf55", termcap: "Fj"},
	{terminfo: "kf56", termcap: "Fk"},
	{terminfo: "kf57", termcap: "Fl"},
	{terminfo: "kf58", termcap: "Fm"},
	{terminfo: "kf59", termcap: "Fn"},
	{terminfo: "kf60", termcap: "Fo"},
	{terminfo: "kf61", termcap: "Fp"},
	{terminfo: "kf62", termcap: "Fq"},
	{terminfo: "kf63", termcap: "Fr"},
	{terminfo: "el1", termcap: "cb"},
	{terminfo: "mgc", termcap: "MC"},
	{terminfo: "smgl", termcap: "ML"},
	{terminfo: "smgr", termcap: "MR"},
	{terminfo: "fln", termcap: "Lf"},
	{terminfo: "sclk", termcap: "SC"},
	{terminfo: "dclk", termcap: "DK"},
	{terminfo: "rmclk", termcap: "RC"},
	{terminfo: "cwin", termcap: "CW"},
	{terminfo: "wingo", termcap: "WG"},
	{terminfo: "hup", termcap: "HU"},
	{terminfo: "dial", termcap: "DI"},
	{terminfo: "qdial", termcap: "QD"},
	{terminfo: "tone", termcap: "TO"},
	{terminfo: "pulse", termcap: "PU"},
	{terminfo: "hook", termcap: "fh"},
	{terminfo: "pause", termcap: "PA"},
	{terminfo: "wait", termcap: "WA"},
	{terminfo: "u0", termcap: "u0"},
	{terminfo: "u1", termcap: "u1"},
	{terminfo: "u2", termcap: "u2"},
	{terminfo: "u3", termcap: "u3"},
	{terminfo: "u4", termcap: "u4"},
	{terminfo: "u5", termcap: "u5"},
	{terminfo: "u6", termcap: "u6"},
	{terminfo: "u7", termcap: "u7"},
	{terminfo: "u8", termcap: "u8"},
	{terminfo: "u9", termcap: "u9"},
	{terminfo: "op", termcap: "op"},
	{terminfo: "oc", termcap: "oc"},
	{terminfo: "initc", termcap: "Ic"},
	{terminfo: "initp", termcap: "Ip"},
	{terminfo: "scp", termcap: "sp"},
	{terminfo: "setf", termcap: "Sf"},
	{terminfo: "setb", termcap: "Sb"},
	{terminfo: "cpi", termcap: "ZA"},
	{terminfo: "lpi", termcap: "ZB"},
	{terminfo: "chr", termcap: "ZC"},
	{terminfo: "cvr", termcap: "ZD"},
	{terminfo: "defc", termcap: "ZE"},
	{terminfo: "swidm", termcap: "ZF"},
	{terminfo: "sdrfq", termcap: "ZG"},
	{terminfo: "sitm", termcap: "ZH"},
	{terminfo: "slm", termcap: "ZI"},
	{terminfo: "smicm", termcap: "ZJ"},
	{terminfo: "snlq", termcap: "ZK"},
	{terminfo: "snrmq", termcap: "ZL"},
	{terminfo: "sshm", termcap: "ZM"},
	{terminfo: "ssubm", termcap: "ZN"},
	{terminfo: "ssupm", termcap: "ZO"},
	{terminfo: "sum", termcap: "ZP"},
	{terminfo: "rwidm", termcap: "ZQ"},
	{terminfo: "ritm", termcap: "ZR"},
	{terminfo: "rlm", termcap: "ZS"},
	{terminfo: "rmicm", termcap: "ZT"},
	{terminfo: "rshm", termcap: "ZU"},
	{terminfo: "rsubm", termcap: "ZV"},
	{terminfo: "rsupm", termcap: "ZW"},
	{terminfo: "rum", termcap: "ZX"},
	{terminfo: "mhpa", termcap: "ZY"},
	{terminfo: "mcud1", termcap: "ZZ"},
	{terminfo: "mcub1", termcap: "Za"},
	{terminfo: "mcuf1", termcap: "Zb"},
	{terminfo: "mvpa", termcap: "Zc"},
	{terminfo: "mcuu1", termcap: "Zd"},
	{terminfo: "porder", termcap: "Ze"},
	{terminfo: "mcud", termcap: "Zf"},
	{terminfo: "mcub", termcap: "Zg"},
	{terminfo: "mcuf", termcap: "Zh"},
	{terminfo: "mcuu", termcap: "Zi"},
	{terminfo: "scs", termcap: "Zj"},
	{terminfo: "smgb", termcap: "Zk"},
	{terminfo: "smgbp", termcap: "Zl"},
	{terminfo: "smglp", termcap: "Zm"},
	{terminfo: "smgrp", termcap: "Zn"},
	{terminfo: "smgt", termcap: "Zo"},
	{terminfo: "smgtp", termcap: "Zp"},
	{terminfo: "sbim", termcap: "Zq"},
	{terminfo: "scsd", termcap: "Zr"},
	{terminfo: "rbim", termcap: "Zs"},
	{terminfo: "rcsd", termcap: "Zt"},
	{terminfo: "subcs", termcap: "Zu"},
	{terminfo: "supcs", termcap: "Zv"},
	{terminfo: "docr", termcap: "Zw"},
	{terminfo: "zerom", termcap: "Zx"},
	{terminfo: "csnm", termcap: "Zy"},
	{terminfo: "kmous", termcap: "Km"},
	{terminfo: "minfo", termcap: "Mi"},
	{terminfo: "reqmp", termcap: "RQ"},
	{terminfo: "getm", termcap: "Gm"},
	{terminfo: "setaf", termcap: "AF"},
	{terminfo: "setab", termcap: "AB"},
	{terminfo: "pfxl", termcap: "xl"},
	{terminfo: "devt", termcap: "dv"},
	{terminfo: "csin", termcap: "ci"},
	{terminfo: "s0ds", termcap: "s0"},
	{terminfo: "s1ds", termcap: "s1"},
	{terminfo: "s2ds", termcap: "s2"},
	{terminfo: "s3ds", termcap: "s3"},
	{terminfo: "smglr", termcap: "ML"},
	{terminfo: "smgtb", termcap: "MT"},
	{terminfo: "birep", termcap: "Xy"},
	{terminfo: "binel", termcap: "Zz"},
	{terminfo: "bicr", termcap: "Yv"},
	{terminfo: "colornm", termcap: "Yw"},
	{terminfo: "defbi", termcap: "Yx"},
	{terminfo: "endbi", termcap: "Yy"},
	{terminfo: "setcolor", termcap: "Yz"},
	{terminfo: "slines", termcap: "YZ"},
	{terminfo: "dispc", termcap: "S1"},
	{terminfo: "smpch", termcap: "S2"},
	{terminfo: "rmpch", termcap: "S3"},
	{terminfo: "smsc", termcap: "S4"},
	{terminfo: "rmsc", termcap: "S5"},
	{terminfo: "pctrm", termcap: "S6"},
	{terminfo: "scesc", termcap: "S7"},
	{terminfo: "scesa", termcap: "S8"},
	{terminfo: "", termcap: ""}, // 386: no name measured; see terminfoUnnamedSlots
	{terminfo: "", termcap: ""}, // 387: no name measured; see terminfoUnnamedSlots
	{terminfo: "", termcap: ""}, // 388: no name measured; see terminfoUnnamedSlots
	{terminfo: "", termcap: ""}, // 389: no name measured; see terminfoUnnamedSlots
	{terminfo: "", termcap: ""}, // 390: no name measured; see terminfoUnnamedSlots
	{terminfo: "", termcap: ""}, // 391: no name measured; see terminfoUnnamedSlots
	{terminfo: "", termcap: ""}, // 392: no name measured; see terminfoUnnamedSlots
	{terminfo: "", termcap: ""}, // 393: no name measured; see terminfoUnnamedSlots
	{terminfo: "OTi2", termcap: "i2"},
	{terminfo: "OTrs", termcap: "rs"},
	{terminfo: "OTnl", termcap: "nl"},
	{terminfo: "OTbc", termcap: "bc"},
	{terminfo: "OTko", termcap: "ko"},
	{terminfo: "OTma", termcap: "ma"},
	{terminfo: "OTG2", termcap: "G2"},
	{terminfo: "OTG3", termcap: "G3"},
	{terminfo: "OTG1", termcap: "G1"},
	{terminfo: "OTG4", termcap: "G4"},
	{terminfo: "OTGR", termcap: "GR"},
	{terminfo: "OTGL", termcap: "GL"},
	{terminfo: "OTGU", termcap: "GU"},
	{terminfo: "OTGD", termcap: "GD"},
	{terminfo: "OTGH", termcap: "GH"},
	{terminfo: "OTGV", termcap: "GV"},
	{terminfo: "OTGC", termcap: "GC"},
	{terminfo: "meml", termcap: "ml"},
	{terminfo: "memu", termcap: "mu"},
}
