// SPDX-FileCopyrightText: 2026 Blair Hamilton
// SPDX-License-Identifier: Apache-2.0

// Package suite runs a real shell's own test suite through both that shell
// and the dialect binary that claims to be it, and reports where they part.
//
// It is the one instrument here whose corpus nobody in this project wrote.
// `make conformance` grades snippets we chose, so it proves that what we
// thought to ask about is right; `make wild` sweeps the scripts installed on
// a machine, which is real code but is not *about* the shell. A shell's own
// suite is thousands of deliberate questions about the shell, written by the
// people who built it, and every one of them was written without knowing this
// implementation exists.
//
// # What may be reported, and what may not
//
// The suites are other projects' expression and CLEANROOM.md's red list
// covers them. The carve-out this instrument stands on is in CLEANROOM.md's
// own words — "where a third-party suite must be run … it is fetched at test
// time and never committed" — and it is a carve-out for *running*, not for
// reading. Running a binary produces facts. A program computing a longest
// common subsequence over bytes is not a person forming a derivative work.
//
// So the report is counts and our own diagnostics, and nothing else:
//
//	may be reported            may not
//	-----------------------    ------------------------------------------
//	strict / parsed / lines    any line, token run or excerpt of a file
//	our parser's own cause,    the fetched text that provoked it
//	  aggregated and ranked
//	how many files a cause     which files, by name or by path
//	  stopped
//	the suite's name+version   anything that helps a reader open one
//
// [Result] therefore carries no file text and no per-file path, and that is
// enforced by its shape rather than by a habit: there is nowhere to put one.
// `make wild` refuses considerably less than this and says why in its own
// output — "a path in a report is an invitation to go look, and looking is
// the one thing the reader must not do" — so this observes the same rule one
// step further out.
//
// # Three numbers, because one misleads in both directions
//
// Strict alone reads as catastrophe: a suite file is hundreds of assertions
// and one disagreement forfeits all of them. Line agreement alone reads as
// triumph, because most lines of most files are prose the shell echoed back.
// Parsed explains the other two — our parser reads a file whole before
// running any of it, so one refused construct forfeits a file that might
// otherwise have agreed on every line, and the gap between parsed and strict
// is the size of *that* effect rather than of our semantics.
//
// # Never the expected-output files
//
// The suites ship their own `.right` files and this never opens one. Partly
// for measurement — they were generated by a different build of a different
// version and disagree with the binary on the machine — and mostly because
// they are the most expression-like part of a suite. The rule is structural
// rather than promised: [Suite.Exclude] keeps them out of the extraction, so
// there is no `.right` file on disk to open by accident.
package suite

import (
	"github.com/blairham/sh/dialect/ash"
	"github.com/blairham/sh/dialect/bash"
	"github.com/blairham/sh/dialect/dash"
	"github.com/blairham/sh/dialect/ksh"
	"github.com/blairham/sh/dialect/zsh"
	"github.com/blairham/sh/syntax"
)

// Suite is one shell's own test suite and everything needed to run it.
//
// It is a table entry on purpose. The multi-dialect shape is the point of
// this instrument: an instrument that could only ever grade bash would bend
// the substrate toward bash, which is the thing this project's premise
// forbids. A column that is not built yet is a row with [Suite.NotYet] set
// and a reason in it, so the report can print what it is *not* measuring —
// a missing column that says nothing reads as a column that passed.
type Suite struct {
	// Name is the suite's shell, as the report prints it.
	Name string
	// Dialect is our dialect binary's name under cmd/, and the key the
	// Makefile target is spelled with: `make bash-suite`.
	Dialect string
	// Version is the release the suite is taken from, pinned so that two
	// runs a month apart are comparable.
	Version string
	// URL is the release archive. Only gzip is read: the standard library
	// has gzip and not xz, and this tree generates rather than imports.
	URL string
	// SHA256 is the archive's digest, lowercase hex. A mismatch stops the
	// run: an instrument that quietly graded whatever arrived is worse than
	// one that did not run.
	SHA256 string
	// Root is the single directory the archive unpacks into.
	Root string
	// Include are the paths under Root that are unpacked, each a directory
	// prefix or an exact file. Everything else in the archive is discarded
	// while streaming, so the shell's own source never lands on the disk at
	// all — this unpacks a suite, not a distribution.
	Include []string
	// Exclude are suffixes never unpacked, whatever Include says. The
	// expected-output files live here: see the package comment.
	Exclude []string
	// TestDir is the directory, under Root, the files are run from.
	TestDir string
	// Ext is the suffix of a file that gets run. Files in TestDir without it
	// are the suite's own fixtures and helpers: present, sourced by the
	// files that need them, never run on their own.
	Ext string
	// Helpers are C programs under Root that the suite calls by name. They
	// are compiled into TestDir. Without them a suite scores zero for
	// reasons that have nothing to do with us — the calls fail identically
	// under both shells, which is agreement on an error message rather than
	// on the shell.
	Helpers []string
	// ShellVar is the environment variable the suite names the shell under
	// test in. It is set to the *shell of the run*, so the reference run
	// re-enters the reference and ours re-enters ours: a suite invokes
	// itself constantly, and pointing this at one shell for both runs would
	// grade the reference against itself.
	ShellVar string
	// Lookup is where the oracle binary might be, in order. The reference
	// shell on the machine is the oracle — never the shipped expected
	// output.
	Lookup []string
	// NotYet, when set, is why this column is a row rather than a run. It is
	// printed.
	NotYet string

	// Ours says the suite is this repository's own, committed and readable,
	// rather than another project's fetched at test time. It is what scopes
	// the no-path rule: see [Suite.attribute].
	Ours bool
	// Dirs are the directories, relative to the suite's root, whose files are
	// run. A fetched suite has one directory and names it in TestDir; ours
	// has two — the shared core/ and the dialect's own — because a core file
	// runs in every column and is the common-denominator claim made
	// executable.
	Dirs []string
}

// Panel is every column, built and unbuilt.
//
// The unbuilt ones carry the work each still needs, stated from what a
// listing of the archive shows rather than from anything inside it. None of
// them is blocked on this instrument's shape, which was the thing worth
// proving: each is a table entry plus an invocation model, not a rewrite.
var Panel = []Suite{
	{
		Name:    "bash",
		Dialect: "bash",
		Version: "5.3",
		URL:     "https://ftp.gnu.org/gnu/bash/bash-5.3.tar.gz",
		SHA256:  "0d5cd86965f869a26cf64f4b71be7b96f90a3ba8b3d74e27e8e9d9d5550f31ba",
		Root:    "bash-5.3",
		// The suite, and the three C programs it calls by name. The
		// helpers live beside the shell's source rather than beside the
		// suite, so naming the directory would unpack the source too.
		Include: []string{
			"tests/",
			"support/recho.c",
			"support/zecho.c",
			"support/printenv.c",
		},
		Exclude:  []string{".right"},
		TestDir:  "tests",
		Ext:      ".tests",
		Helpers:  []string{"support/recho.c", "support/zecho.c", "support/printenv.c"},
		ShellVar: "THIS_SH",
		Lookup:   []string{"/opt/homebrew/bin/bash", "/usr/local/bin/bash", "/bin/bash", "/usr/bin/bash"},
	},
	{
		Name:    "zsh",
		Dialect: "zsh",
		Version: "5.9",
		URL:     "https://sourceforge.net/projects/zsh/files/zsh/5.9/zsh-5.9.tar.xz/download",
		SHA256:  "9b8d1ecedd5b5e81fbf1918e876752a7dd948e05c1a0dba10ab863842d45acd5",
		Root:    "zsh-5.9",
		Include: []string{"Test/"},
		TestDir: "Test",
		Ext:     ".ztst",
		Lookup:  []string{"/opt/homebrew/bin/zsh", "/usr/local/bin/zsh", "/bin/zsh", "/usr/bin/zsh"},
		NotYet: "the 73 files are .ztst, a format of the suite's own that a shell does not " +
			"run — so this column needs an invocation model rather than a table row, and " +
			"the release ships .tar.xz where the standard library reads gzip",
	},
	{
		Name:    "ksh93",
		Dialect: "ksh",
		Version: "1.0.10",
		URL:     "https://github.com/ksh93/ksh/archive/refs/tags/v1.0.10.tar.gz",
		SHA256:  "9f4c7a9531cec6941d6a9fd7fb70a4aeda24ea32800f578fd4099083f98b4e8a",
		Root:    "ksh-1.0.10",
		Include: []string{"src/cmd/ksh93/tests/"},
		TestDir: "src/cmd/ksh93/tests",
		Ext:     ".sh",
		Lookup:  []string{"/bin/ksh", "/usr/bin/ksh", "/opt/homebrew/bin/ksh93"},
		NotYet: "the maintained suite is ksh93u+m's and the only ksh93 on a Mac is AT&T 93u+ " +
			"from 2012, so the oracle and the suite are different lineages — the run would " +
			"measure the fork rather than us. It needs a ksh93u+m binary on the machine first",
	},
	{
		Name:    "dash",
		Dialect: "dash",
		Version: "",
		NotYet: "dash ships no test suite of its own; what it has is the POSIX conformance " +
			"corpus it borrows, which is not the shell's own questions about itself",
	},
}

// Built is the columns that can run.
func Built() []Suite {
	var built []Suite
	for _, s := range Panel {
		if s.NotYet == "" {
			built = append(built, s)
		}
	}
	return built
}

// Find is the panel entry for a dialect name.
func Find(dialect string) (Suite, bool) {
	for _, s := range Panel {
		if s.Dialect == dialect {
			return s, true
		}
	}
	return Suite{}, false
}

// Syntax is the parser configuration a column's files are read with.
//
// It is the same [syntax.Dialect] the matching binary under cmd/ is built
// from, which is what lets the parsed figure be a statement about the binary
// while being measured with the library: the binary has no second parser.
func (s Suite) Syntax() (syntax.Dialect, bool) {
	switch s.Dialect {
	case "bash":
		return bash.Dialect(), true
	case "zsh":
		return zsh.Dialect(), true
	case "ksh":
		return ksh.Dialect(), true
	case "dash":
		return dash.Dialect(), true
	case "ash":
		return ash.Dialect(), true
	default:
		return syntax.Dialect{}, false
	}
}
