// SPDX-FileCopyrightText: 2026 Blair Hamilton
// SPDX-License-Identifier: Apache-2.0

package oracle

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
)

// A baseline is the committed list of cases a dialect binary does not yet
// match exactly, one case ID per line. It is what turns the conformance
// number into a gate without failing on unfinished work: a case outside the
// list that fails is a regression, and a case on the list that passes is a
// fix the list has not been told about (#5710).
//
// Per case and not a count. A total that falls can hide a row that rose —
// one fix paying for one regression reads as no change, or as progress — and
// only a list says which row moved.

// Failing is the IDs of the cases that did not match exactly, sorted.
func (r *Report) Failing() []string {
	var out []string
	for _, m := range r.Matches {
		if !m.OK {
			out = append(out, m.CaseID)
		}
	}
	sort.Strings(out)
	return out
}

// Answers is what a graded case expected and what it got, as the two lines
// -v prints for it, or "" for a case the run did not grade.
//
// The ratchet prints these under every case it reports as regressed, because
// a regression the log names without its answers can only be investigated by
// reproducing it, and one that does not reproduce is then a name and nothing
// else. That was #6118: one red run in the ksh ratchet, green on rerun and in
// thousands of local runs, and no record anywhere of what the shell had said.
func (r *Report) Answers(id string) string {
	for _, m := range r.Matches {
		if m.CaseID == id {
			return fmt.Sprintf("    want %s\n    got  %s\n", describe(m.Want), describe(m.Got))
		}
	}
	return ""
}

// Ratchet compares a run's failing cases with a baseline. regressed are
// failing and not listed; fixed are listed and passing. Only the cases the
// run graded take part, so a run narrowed with -only checks only its own
// slice of the list.
func Ratchet(r *Report, baseline []string) (regressed, fixed []string) {
	graded := make(map[string]bool, len(r.Matches))
	failing := make(map[string]bool)
	for _, m := range r.Matches {
		graded[m.CaseID] = true
		if !m.OK {
			failing[m.CaseID] = true
		}
	}
	listed := make(map[string]bool, len(baseline))
	for _, id := range baseline {
		listed[id] = true
		if graded[id] && !failing[id] {
			fixed = append(fixed, id)
		}
	}
	for id := range failing {
		if !listed[id] {
			regressed = append(regressed, id)
		}
	}
	sort.Strings(regressed)
	sort.Strings(fixed)
	return regressed, fixed
}

// LoadBaseline reads a baseline file. Blank lines and lines starting with #
// are ignored. A missing file is an error rather than an empty list: an empty
// list is the claim that every case passes, and a typo in a path must not be
// able to make it.
func LoadBaseline(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()
	var out []string
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	return out, sc.Err()
}

// WriteBaseline writes the run's failing cases as a baseline.
func WriteBaseline(path, against string, r *Report) error {
	var b strings.Builder
	fmt.Fprintf(&b, "# Cases the binary graded against %s does not yet match exactly.\n", against)
	b.WriteString("# Generated by `make conformance-baseline`; a fix removes its line, and CI\n")
	b.WriteString("# fails on a case that fails without being listed or passes while listed.\n")
	for _, id := range r.Failing() {
		b.WriteString(id)
		b.WriteByte('\n')
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
