// SPDX-FileCopyrightText: 2026 Blair Hamilton
// SPDX-License-Identifier: Apache-2.0

package oracle

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// Run is one execution of the corpus across the panel present on a machine.
type Run struct {
	Shells  []ShellRecord `json:"shells"`
	Missing []string      `json:"missing,omitempty"`
	// Results is caseID -> shellName -> result.
	Results map[string]map[string]Result `json:"results"`
}

// ShellRecord is what the panel looked like when the run happened.
type ShellRecord struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// Execute runs every case in every shell that is present.
func Execute(ctx context.Context, cases []Case) (*Run, error) {
	found, missing := Resolve(ctx)
	if len(found) == 0 {
		return nil, fmt.Errorf("no reference shells found; the panel is %d shells and none are installed", len(Panel))
	}

	r := &Run{Missing: missing, Results: make(map[string]map[string]Result, len(cases))}
	for _, sh := range found {
		r.Shells = append(r.Shells, ShellRecord{Name: sh.Name, Version: sh.Version})
	}
	for _, c := range cases {
		row := make(map[string]Result, len(found))
		for _, sh := range found {
			row[sh.Name] = Exec(ctx, sh, c)
		}
		r.Results[c.ID] = row
	}
	return r, nil
}

// Markdown renders the run as the generated half of docs/spec.
//
// The prose in docs/spec is written by hand and stays that way; only the
// measurements are generated. A generator that also owned the analysis would
// either overwrite it or be unable to regenerate at all.
func (r *Run) Markdown(cases []Case) string {
	var b strings.Builder
	b.WriteString("# Measurements\n\n")
	b.WriteString("*Generated by `make oracle` from `internal/oracle`. Do not edit by hand.*\n\n")
	b.WriteString("Every table in the rest of `docs/spec` should be derivable from a row\n")
	b.WriteString("here. A spec claim with no case behind it is a claim nobody can re-check.\n\n")

	b.WriteString("## Panel\n\n| shell | build |\n| --- | --- |\n")
	for _, s := range r.Shells {
		fmt.Fprintf(&b, "| `%s` | %s |\n", s.Name, s.Version)
	}
	if len(r.Missing) > 0 {
		fmt.Fprintf(&b, "\n**Not present on the machine that generated this: %s.**\n",
			"`"+strings.Join(r.Missing, "`, `")+"`")
		b.WriteString("Those columns are absent below rather than empty — a table from a\n")
		b.WriteString("narrower panel is a weaker claim, and saying so is the point.\n")
	}
	b.WriteString("\n")

	names := make([]string, len(r.Shells))
	for i, s := range r.Shells {
		names[i] = s.Name
	}

	for _, cat := range categories(cases) {
		fmt.Fprintf(&b, "## %s\n\n", cat)
		b.WriteString("| case | " + strings.Join(names, " | ") + " |\n")
		b.WriteString("| --- |" + strings.Repeat(" --- |", len(names)) + "\n")
		for _, c := range cases {
			if c.Category != cat {
				continue
			}
			fmt.Fprintf(&b, "| `%s` |", c.ID)
			for _, n := range names {
				fmt.Fprintf(&b, " %s |", cell(r.Results[c.ID][n]))
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
		for _, c := range cases {
			if c.Category == cat {
				fmt.Fprintf(&b, "- `%s` — %s\n  ```sh\n%s\n  ```\n", c.ID, c.Why,
					indentSnippet(c.Snippet))
			}
		}
		b.WriteString("\n")
	}
	// Exactly one trailing newline: the generated file is committed, and a
	// hook that keeps rewriting it would fail the commit on every
	// regeneration.
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func cell(res Result) string {
	switch {
	case res.TimedOut:
		return "*(timeout)*"
	case res.Output == "":
		return fmt.Sprintf("*(no output, status %d)*", res.Status)
	}
	out := strings.ReplaceAll(res.Output, "|", "\\|")
	if res.Status != 0 {
		return fmt.Sprintf("`%s` *(status %d)*", out, res.Status)
	}
	return "`" + out + "`"
}

func categories(cases []Case) []string {
	seen := map[string]bool{}
	var out []string
	for _, c := range cases {
		if !seen[c.Category] {
			seen[c.Category] = true
			out = append(out, c.Category)
		}
	}
	return out
}

// Save writes the golden record.
func (r *Run) Save(path string) error {
	b, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

// Load reads a golden record.
func Load(path string) (*Run, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var r Run
	if err := json.Unmarshal(b, &r); err != nil {
		return nil, err
	}
	return &r, nil
}

// Drift is one case whose behavior moved.
type Drift struct {
	CaseID string
	Shell  string
	Was    Result
	Now    Result
}

func (d Drift) String() string {
	return fmt.Sprintf("%s [%s]\n    was: %q (status %d)\n    now: %q (status %d)",
		d.CaseID, d.Shell, d.Was.Output, d.Was.Status, d.Now.Output, d.Now.Status)
}

// Compare reports where this run differs from the golden record.
//
// Only shells present in both are compared. A shell missing from one side is
// not drift: CI and a laptop have different panels, and failing on that would
// make the check useless exactly where it is most wanted.
func (r *Run) Compare(golden *Run) []Drift {
	var out []Drift
	for id, now := range r.Results {
		was, ok := golden.Results[id]
		if !ok {
			continue // a new case has nothing to drift from
		}
		for sh, nowRes := range now {
			wasRes, ok := was[sh]
			if !ok {
				continue
			}
			if wasRes != nowRes {
				out = append(out, Drift{CaseID: id, Shell: sh, Was: wasRes, Now: nowRes})
			}
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].CaseID != out[j].CaseID {
			return out[i].CaseID < out[j].CaseID
		}
		return out[i].Shell < out[j].Shell
	})
	return out
}

// NewCases returns case IDs absent from the golden record.
func (r *Run) NewCases(golden *Run) []string {
	var out []string
	for id := range r.Results {
		if _, ok := golden.Results[id]; !ok {
			out = append(out, id)
		}
	}
	sort.Strings(out)
	return out
}

// indentSnippet puts a snippet inside a fenced block.
//
// Blank lines are left blank rather than indented. Replacing every newline
// with a newline and two spaces was simpler and indented the empty line a
// trailing newline leaves behind, so every regeneration of this file added
// thirteen lines of trailing whitespace for the commit hook to strip — and a
// commit that a hook rewrites is a commit that does not happen.
func indentSnippet(s string) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = "  " + line
		}
	}
	return strings.Join(lines, "\n")
}
