// SPDX-FileCopyrightText: 2026 Blair Hamilton
// SPDX-License-Identifier: Apache-2.0

package oracle

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// Run is one execution of the corpus across the panel present on a machine.
type Run struct {
	Shells  []ShellRecord `json:"shells"`
	Missing []string      `json:"missing,omitempty"`
	// Results is caseID -> shellName -> result.
	Results map[string]map[string]Result `json:"results"`
}

// ShellRecord is what the panel looked like when the run happened.
type ShellRecord struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// Execute runs every case in every shell that is present.
func Execute(ctx context.Context, cases []Case) (*Run, error) {
	found, missing := Resolve(ctx)
	if len(found) == 0 {
		return nil, fmt.Errorf("no reference shells found; the panel is %d shells and none are installed", len(Panel))
	}

	r := &Run{Missing: missing, Results: make(map[string]map[string]Result, len(cases))}
	for _, sh := range found {
		r.Shells = append(r.Shells, ShellRecord{Name: sh.Name, Version: sh.Version})
	}
	for _, c := range cases {
		row := make(map[string]Result, len(found))
		for _, sh := range found {
			row[sh.Name] = Exec(ctx, sh, c)
		}
		r.Results[c.ID] = row
	}
	return r, nil
}

// Markdown renders the run as the generated half of docs/spec.
//
// The prose in docs/spec is written by hand and stays that way; only the
// measurements are generated. A generator that also owned the analysis would
// either overwrite it or be unable to regenerate at all.
func (r *Run) Markdown(cases []Case) string {
	var b strings.Builder
	b.WriteString("# Measurements\n\n")
	b.WriteString("*Generated by `make oracle` from `internal/oracle`. Do not edit by hand.*\n\n")
	b.WriteString("Every table in the rest of `docs/spec` should be derivable from a row\n")
	b.WriteString("here. A spec claim with no case behind it is a claim nobody can re-check.\n\n")
	b.WriteString("A cell reads as standard output first, then whatever the shell wrote to\n")
	b.WriteString("standard error after a bold **2>**. The two streams are captured apart,\n")
	b.WriteString("so a diagnostic that moved from one to the other shows up here as a\n")
	b.WriteString("changed cell rather than as no change at all. Newlines are shown as `~`.\n\n")
	b.WriteString("A case marked **(refusal)** is *graded* on the fact that the shell said\n")
	b.WriteString("no — same outcome, same standard output, and a diagnostic on standard\n")
	b.WriteString("error from both sides — rather than on the words it said no in, which\n")
	b.WriteString("are a dialect's own. Only the grading is relaxed: the cells below are\n")
	b.WriteString("what each shell actually printed, and the drift check still compares\n")
	b.WriteString("every byte of them.\n\n")
	b.WriteString("A case marked **(unordered)** is one the reference shells answer two\n")
	b.WriteString("ways at random, because the shell being measured races with itself.\n")
	b.WriteString("Its cells are one sample rather than the answer, so they are *kept* by\n")
	b.WriteString("a regeneration instead of resampled: re-rolling a coin on every run is\n")
	b.WriteString("the only way such a row can move, and every move is noise. Nothing\n")
	b.WriteString("grades it and nothing drift-checks it either, for the same reason.\n\n")

	b.WriteString("## Panel\n\n| shell | build |\n| --- | --- |\n")
	for _, s := range r.Shells {
		fmt.Fprintf(&b, "| `%s` | %s |\n", s.Name, s.Version)
	}
	if len(r.Missing) > 0 {
		fmt.Fprintf(&b, "\n**Not present on the machine that generated this: %s.**\n",
			"`"+strings.Join(r.Missing, "`, `")+"`")
		b.WriteString("Those columns are absent below rather than empty — a table from a\n")
		b.WriteString("narrower panel is a weaker claim, and saying so is the point.\n")
	}
	b.WriteString("\n")

	names := make([]string, len(r.Shells))
	for i, s := range r.Shells {
		names[i] = s.Name
	}

	for _, cat := range categories(cases) {
		fmt.Fprintf(&b, "## %s\n\n", cat)
		b.WriteString("| case | " + strings.Join(names, " | ") + " |\n")
		b.WriteString("| --- |" + strings.Repeat(" --- |", len(names)) + "\n")
		for _, c := range cases {
			if c.Category != cat {
				continue
			}
			fmt.Fprintf(&b, "| `%s`%s |", c.ID, gradeMark(c))
			for _, n := range names {
				fmt.Fprintf(&b, " %s |", cell(r.Results[c.ID][n]))
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
		for _, c := range cases {
			if c.Category == cat {
				fmt.Fprintf(&b, "- `%s`%s — %s\n  ```sh\n%s\n  ```\n", c.ID, gradeMark(c), c.Why,
					indentSnippet(c.Snippet))
			}
		}
		b.WriteString("\n")
	}
	// Exactly one trailing newline: the generated file is committed, and a
	// hook that keeps rewriting it would fail the commit on every
	// regeneration.
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// cell renders one result into one table cell.
//
// The stream marker is bold and therefore outside the code span, which is the
// reason to spell it that way: a shell can print the characters `2>` and a
// reader still has to be able to tell that from the harness saying "the rest
// of this came out on standard error".
func cell(res Result) string {
	switch {
	case res.TimedOut:
		return "*(timeout)*"
	case res.Stdout == "" && res.Stderr == "":
		return fmt.Sprintf("*(no output, %s)*", outcome(res))
	}
	var parts []string
	if res.Stdout != "" {
		parts = append(parts, "`"+escapeCell(res.Stdout)+"`")
	}
	if res.Stderr != "" {
		parts = append(parts, "**2>** `"+escapeCell(res.Stderr)+"`")
	}
	out := strings.Join(parts, " ")
	if res.Signal != 0 || res.Status != 0 {
		return fmt.Sprintf("%s *(%s)*", out, outcome(res))
	}
	return out
}

// outcome names how the shell ended: the signal that killed it, or the status
// it exited with.
//
// The two are alternatives rather than a pair — there is no exit status for a
// process a signal ended — so printing the status of a signal death would be
// printing the -1 that stands for its absence.
//
// The number and the recording machine's word for it, because neither alone is
// enough: the number is not the same on two operating systems for the signals
// above the standard set, and the word is the fact a reader wants but is a
// description rather than a name — the word for SIGKILL is "killed", which
// says nothing on its own.
//
// The word comes out of the record beside the number rather than from
// syscall.Signal.String() here. Asking the local kernel meant the two halves
// of one cell came from two machines — signal 30 is SIGUSR1 on macOS and
// SIGPWR on Linux — and made this document not quite a pure function of the
// record (#776). A record from before the field renders the bare number.
func outcome(res Result) string {
	if res.Signal != 0 {
		if res.SignalName == "" {
			return fmt.Sprintf("killed by signal %d", int(res.Signal))
		}
		return fmt.Sprintf("killed by signal %d (%s)", int(res.Signal), res.SignalName)
	}
	return fmt.Sprintf("status %d", res.Status)
}

// gradeMark labels a row that is graded on something other than an exact
// comparison, next to the case's own name in both places the name appears.
//
// The record has to carry this. A relaxation visible only in the corpus source
// is one a reader of the generated tables cannot see, and the whole objection
// to grading a refusal loosely is that it could quietly turn a divergence
// green — an objection that only stands while nobody can tell which rows are
// which.
//
// A row can carry more than one mark, so they are joined rather than chosen
// between: the two say different things, and a reader who is shown only the
// first would draw the wrong conclusion about the other.
func gradeMark(c Case) string {
	var marks []string
	if c.GradedOnRefusal {
		marks = append(marks, "**(refusal)**")
	}
	if c.ReferenceRaces {
		marks = append(marks, "**(unordered)**")
	}
	if len(marks) == 0 {
		return ""
	}
	return " " + strings.Join(marks, " ")
}

// escapeCell hides the one character a Markdown table reads as structure.
func escapeCell(s string) string { return strings.ReplaceAll(s, "|", "\\|") }

func categories(cases []Case) []string {
	seen := map[string]bool{}
	var out []string
	for _, c := range cases {
		if !seen[c.Category] {
			seen[c.Category] = true
			out = append(out, c.Category)
		}
	}
	return out
}

// Record writes both generated artifacts from one run, carrying forward
// whatever prev holds for the rows that race. prev may be nil, which is the
// first regeneration on a machine that has no record yet.
//
// One entry point rather than three calls at the call site, because the
// *order* is the part that is easy to get wrong and impossible to see: the
// document is rendered from the same Run the record is saved from, so pinning
// after rendering would leave a stable golden.json beside a measurements.md
// that still churned. Nothing about the two writes says so on its own.
func (r *Run) Record(prev *Run, cases []Case, docPath, goldenPath string) error {
	r.KeepRacingRows(prev, cases)
	if err := os.WriteFile(docPath, []byte(r.Markdown(cases)), 0o644); err != nil {
		return err
	}
	return r.Save(goldenPath)
}

// Save writes the golden record.
func (r *Run) Save(path string) error {
	b, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

// KeepRacingRows carries a racing case's recorded cells forward from prev.
//
// A case marked Case.ReferenceRaces is one the reference answers two ways at
// random, so what a run observes for it is a coin flip rather than a
// measurement. Nothing grades such a row and nothing drift-checks it — but
// regeneration still *wrote* whatever the coin said, which is the one way the
// row could move, and every move was noise. Measured on this corpus's single
// racing row, `set -x; echo a | cat`: ksh93 reorders its two trace lines 41
// times in 400, bash 5 in 200 and zsh 1 in 200, so roughly one regeneration in
// eight rewrote a cell nobody was reading. That landed in a pull request about
// something else, and a reviewer comparing failing sets had to recognize it as
// noise before ignoring it — the cost this removes.
//
// Kept only where the shell is the same build. A version that moved is a
// reason to look again even at a row nothing checks, and it is the one event
// that makes the old sample stale rather than merely unlucky. A shell prev
// never saw, and a case prev never had, are recorded fresh: this pins a value
// that exists and never invents one.
func (r *Run) KeepRacingRows(prev *Run, cases []Case) {
	if prev == nil {
		return
	}
	same := sameBuild(r, prev)
	for _, c := range cases {
		if !c.ReferenceRaces {
			continue
		}
		was, recorded := prev.Results[c.ID]
		now, ran := r.Results[c.ID]
		if !recorded || !ran {
			continue
		}
		for sh, res := range was {
			if _, present := now[sh]; present && same[sh] {
				now[sh] = res
			}
		}
	}
}

// sameBuild reports, per shell, whether the two runs saw the same build of it.
func sameBuild(now, prev *Run) map[string]bool {
	was := make(map[string]string, len(prev.Shells))
	for _, s := range prev.Shells {
		was[s.Name] = s.Version
	}
	out := make(map[string]bool, len(now.Shells))
	for _, s := range now.Shells {
		v, seen := was[s.Name]
		out[s.Name] = seen && v == s.Version
	}
	return out
}

// Load reads a golden record.
func Load(path string) (*Run, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var r Run
	if err := json.Unmarshal(b, &r); err != nil {
		return nil, err
	}
	return &r, nil
}

// Drift is one case whose behavior moved.
type Drift struct {
	CaseID string
	Shell  string
	Was    Result
	Now    Result
}

func (d Drift) String() string {
	return fmt.Sprintf("%s [%s]\n    was: %s\n    now: %s",
		d.CaseID, d.Shell, describe(d.Was), describe(d.Now))
}

// describe is one result on one line, for a report a person reads.
//
// Standard error is named rather than merged in, so "the message moved
// streams" is legible as such instead of looking like two identical results.
func describe(r Result) string {
	if r.TimedOut {
		return "(timeout)"
	}
	return fmt.Sprintf("out %q err %q (%s)", r.Stdout, r.Stderr, outcome(r))
}

// Compare reports where this run differs from the golden record.
//
// Only shells present in both are compared. A shell missing from one side is
// not drift: CI and a laptop have different panels, and failing on that would
// make the check useless exactly where it is most wanted.
func (r *Run) Compare(golden *Run) []Drift {
	racy := map[string]bool{}
	for _, c := range Corpus {
		if c.ReferenceRaces {
			racy[c.ID] = true
		}
	}
	var out []Drift
	for id, now := range r.Results {
		was, ok := golden.Results[id]
		if !ok {
			continue // a new case has nothing to drift from
		}
		if racy[id] {
			// Nothing to drift from either: the recorded value was one of
			// two answers the shell gives at random, so a disagreement with
			// it is the coin landing the other way rather than a shell that
			// changed.
			continue
		}
		for sh, nowRes := range now {
			wasRes, ok := was[sh]
			if !ok {
				continue
			}
			if wasRes != nowRes {
				out = append(out, Drift{CaseID: id, Shell: sh, Was: wasRes, Now: nowRes})
			}
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].CaseID != out[j].CaseID {
			return out[i].CaseID < out[j].CaseID
		}
		return out[i].Shell < out[j].Shell
	})
	return out
}

// NewCases returns case IDs absent from the golden record.
func (r *Run) NewCases(golden *Run) []string {
	var out []string
	for id := range r.Results {
		if _, ok := golden.Results[id]; !ok {
			out = append(out, id)
		}
	}
	sort.Strings(out)
	return out
}

// indentSnippet puts a snippet inside a fenced block.
//
// Blank lines are left blank rather than indented. Replacing every newline
// with a newline and two spaces was simpler and indented the empty line a
// trailing newline leaves behind, so every regeneration of this file added
// thirteen lines of trailing whitespace for the commit hook to strip — and a
// commit that a hook rewrites is a commit that does not happen.
func indentSnippet(s string) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = "  " + line
		}
	}
	return strings.Join(lines, "\n")
}
